"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ ](bg:mauve fg:white)\
$username\
$directory\
$time\
[](bg:none fg:mauve) \
"""

palette = 'catppuccin_mocha'

[username]
show_always = true
style_user = "bg:mauve fg:bold crust"
style_root = "bg:mauve fg:bold crust"
format = '[ $user]($style)'

[directory]
style = "bg:mauve fg:bold crust"
format = "[ $path]($style)"
home_symbol = "~"
truncation_length = 0
truncate_to_repo = false

[time]
disabled = false
time_format = "%R"
style = "bg:mauve fg:bold crust"
format = '[ $time ]($style)'

[line_break]
disabled = false

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
